// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: TSPi_ActionCamera
//ui_Screen1.c

#include "../ui.h"
#include <gst/gst.h>
#include <gst/app/gstappsink.h>
#include <stdio.h>

// GStreamer pipeline elements
static GstElement *pipeline, *source, *capsfilter, *sink;
static GstBus *bus;

static void record_btn_event_cb(lv_event_t *e)
{
    printf("start\n");
}

// GStreamer error handling callback
static void handle_gstreamer_error(GstBus *bus, GstMessage *msg)
{
    GError *err = NULL;
    gchar *debug_info = NULL;
    gst_message_parse_error(msg, &err, &debug_info);
    fprintf(stderr, "GStreamer Error: %s (%s)\n", err->message, debug_info ? debug_info : "no debug info");
    g_clear_error(&err);
    g_free(debug_info);
}

void ui_Screen1_screen_init(void)
{
    // Get screen dimensions
    lv_display_t *disp = lv_display_get_default();
    int32_t hor_res = lv_display_get_horizontal_resolution(disp);
    int32_t ver_res = lv_display_get_vertical_resolution(disp);
    LV_LOG_USER("DISPLAY: %dx%d", hor_res, ver_res);

    // Create full-screen main screen
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_set_style_pad_all(ui_Screen1, 0, LV_PART_MAIN);
    lv_obj_set_style_margin_all(ui_Screen1, 0, LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_Screen1, 0, LV_PART_MAIN);
    lv_obj_set_style_radius(ui_Screen1, 0, LV_PART_MAIN);
    lv_obj_set_size(ui_Screen1, hor_res, ver_res);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN);

    // Create full-screen video container
    lv_obj_t *video_container = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(video_container);
    lv_obj_set_size(video_container, hor_res, ver_res);
    lv_obj_set_pos(video_container, 0, 0);
    lv_obj_set_style_bg_color(video_container, lv_color_hex(0x222222), LV_PART_MAIN);

    // Create video preview area
    lv_obj_t *video_area = lv_obj_create(video_container);
    lv_obj_remove_style_all(video_area);
    lv_obj_set_size(video_area, hor_res, ver_res - 30); // Reserve 30px for bottom bar
    lv_obj_set_pos(video_area, 0, 0);
    lv_obj_set_style_bg_color(video_area, lv_color_hex(0x222222), LV_PART_MAIN);
    lv_obj_set_style_border_width(video_area, 0, LV_PART_MAIN);

    // Bottom semi-transparent control bar
    lv_obj_t *bottom_bar = lv_obj_create(video_container);
    lv_obj_remove_style_all(bottom_bar);
    lv_obj_set_size(bottom_bar, hor_res, 30);
    lv_obj_set_pos(bottom_bar, 0, ver_res - 30);
    lv_obj_set_style_bg_color(bottom_bar, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(bottom_bar, LV_OPA_50, LV_PART_MAIN);

    // "ActionCAM" text
    lv_obj_t *brand_label = lv_label_create(bottom_bar);
    lv_label_set_text(brand_label, "ActionCAM");
    lv_obj_align(brand_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_text_font(brand_label, &lv_font_montserrat_20, LV_PART_MAIN);
    lv_obj_set_style_text_color(brand_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN);

    // Record button
    lv_obj_t *record_btn = lv_button_create(video_container);
    lv_obj_set_size(record_btn, 60, 60);
    lv_obj_align(record_btn, LV_ALIGN_RIGHT_MID, -20, -15);
    lv_obj_set_style_radius(record_btn, 30, LV_PART_MAIN);
    lv_obj_set_style_bg_color(record_btn, lv_color_hex(0xFF0000), LV_PART_MAIN);
    lv_obj_add_event_cb(record_btn, record_btn_event_cb, LV_EVENT_CLICKED, NULL);

    // Record button text
    lv_obj_t *record_label = lv_label_create(record_btn);
    lv_label_set_text(record_label, "REC");
    lv_obj_center(record_label);
    lv_obj_set_style_text_color(record_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(record_label, &lv_font_montserrat_16, LV_PART_MAIN);

    // Initialize GStreamer
    gst_init(NULL, NULL);

    // Create GStreamer pipeline
    pipeline = gst_pipeline_new("video-pipeline");
    source = gst_element_factory_make("v4l2src", "source");
    capsfilter = gst_element_factory_make("capsfilter", "capsfilter");
    sink = gst_element_factory_make("kmssink", "sink");

    if (!pipeline || !source || !capsfilter || !sink) {
        fprintf(stderr, "Failed to create GStreamer elements\n");
        return;
    }

    // Configure source
    g_object_set(G_OBJECT(source), "device", "/dev/video0", NULL);

    // Configure capsfilter for 800x450 (leaving 30px for bottom bar)
    GstCaps *caps = gst_caps_new_simple("video/x-raw",
                                        "format", G_TYPE_STRING, "RGB",
                                        "width", G_TYPE_INT, hor_res,
                                        "height", G_TYPE_INT, ver_res - 30,
                                        "framerate", GST_TYPE_FRACTION, 30, 1,
                                        NULL);
    g_object_set(G_OBJECT(capsfilter), "caps", caps, NULL);
    gst_caps_unref(caps);

    // Configure kmssink
    g_object_set(G_OBJECT(sink), "driver-name", "tidss", "render-rectangle", "{0,0,800,450}", NULL);

    // Link pipeline elements
    gst_bin_add_many(GST_BIN(pipeline), source, capsfilter, sink, NULL);
    if (!gst_element_link_many(source, capsfilter, sink, NULL)) {
        fprintf(stderr, "Failed to link GStreamer elements\n");
        gst_object_unref(pipeline);
        return;
    }

    // Start the pipeline
    GstStateChangeReturn ret = gst_element_set_state(pipeline, GST_STATE_PLAYING);
    if (ret == GST_STATE_CHANGE_FAILURE) {
        fprintf(stderr, "Unable to start GStreamer pipeline\n");
        gst_object_unref(pipeline);
        return;
    }

    // Set up bus to handle errors
    bus = gst_pipeline_get_bus(GST_PIPELINE(pipeline));
    gst_bus_add_signal_watch(bus);
    g_signal_connect(bus, "message::error", G_CALLBACK(handle_gstreamer_error), NULL);

    // Load the screen
    lv_scr_load(ui_Screen1);
}