/*
 * @Author: LegionMay
 * @FilePath: /TSPi_Action/lv_port_linux/ui/ui.h
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: TSPi_ActionCamera

#ifndef _TSPI_ACTIONCAMERA_UI_H
#define _TSPI_ACTIONCAMERA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Roller2;
// CUSTOM VARIABLES
extern lv_obj_t *ui_Screen2;
void ui_Screen2_screen_init(void);
// extern lv_obj_t *ui_FileList;
// void ui_FileList_screen_init(void);
// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void my_ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
